### ISSUE TITLE
Doesn't work with windows

### ISSUE THREAD

**Issue by samoht** [dinosaure/checkseum#7]
See https://github.com/fdopen/opam-repository-mingw/commit/857a012189c005ac2c0aef4c96f64abf990a12ab

**Comment by dinosaure** [comment]
The definition of `size_t` is come from [`zlib`](https://github.com/madler/zlib/blob/master/zconf.h#L240). We can put an other branch `if defined(WIN32)` and include the window definition of `size_t` however, I'm not sure about that and I need a window super developer (@dra27 or @nojb) to have a advise on the best way to have the window support.

**Comment by nojb** [comment]
Typically one can use the type `SIZE_T` on Windows instead (defined in `BaseTsd.h`).

**Comment by dinosaure** [comment]
See #8 but I need to put some tests on window and unix.
